{{- range $vo, $token := .Values.cloudkeeper.auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudkeeper-secret-{{ $vo }}
type: Opaque
data:
  token: {{ $token | b64enc | quote }}
{{- end }}
