{{- $values := .Values -}}
{{- range $site, $siteConf := .Values.sites }}
{{- range $vo, $share := $siteConf.vos }}
{{- if $share.auth.cloudkeeper }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ck-os-{{ $site | lower }}-{{ $vo | lower }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ck-os-{{ $site | lower }}-{{ $vo | lower | replace "." "-" }}
  template:
    metadata:
      labels:
        app: ck-os-{{ $site | lower }}-{{ $vo | lower | replace "." "-" }}
    spec:
      containers:
        - name: cloudkeeper-os
          image: {{ $values.cloudkeeperOS.image.repository }}:{{ $values.cloudkeeperOS.image.tag }}
          imagePullPolicy: {{ $values.cloudkeeperOS.image.pullPolicy }}
          command:
          - cloudkeeper-os
          - --openstack-oidc-client-id
          - $(CHECKIN_CLIENT_ID)
          - --openstack-oidc-client-secret
          - $(CHECKIN_CLIENT_SECRET)
          - --openstack-oidc-refresh-token
          - $(CHECKIN_REFRESH_TOKEN)
          - --openstack-auth-type
          - v3oidcrefreshtoken
          - --openstack-oidc-protocol
          - {{ $siteConf.protocol | default "openid" }}
          - --openstack-oidc-identity-provider
          - egi.eu
          - --openstack-auth-url
          - {{ $siteConf.endpoint }}
          - --openstack-oidc-discovery-endpoint
          - https://aai.egi.eu/oidc/.well-known/openid-configuration
          - --openstack-project-id
          - {{ $share.auth.project }}
          - --connection-listen-address
          - 0.0.0.0:50051
          env:
          - name: CHECKIN_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: checkin-cloudkeeper-creds-{{ $site | lower }}-{{ $vo | lower }}
                key: client_id
          - name: CHECKIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: checkin-cloudkeeper-creds-{{ $site | lower }}-{{ $vo | lower }}
                key: client_secret
          - name: CHECKIN_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: checkin-cloudkeeper-creds-{{ $site | lower }}-{{ $vo | lower }}
                key: refresh_token 
          ports:
            - containerPort: 50051
          resources:
{{ toYaml $values.resources | indent 12 }}
{{- end }}
{{- end }}
{{- end }}
