---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: pycontribs/ubuntu:latest
    pre_build_image: true
lint: ansible-lint --exclude .github/
provisioner:
  name: ansible
verifier:
  name: testinfra
