---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:latest
lint: ansible-lint --exclude .github/
provisioner:
  name: ansible
verifier:
  name: testinfra
