# Disk layout
disk_setup:
  sdb:
    table_type: 'mbr'
    layout: true
    overwrite: false
fs_setup:
  - filesystem: ext4
    device: sdb
    partition: any
    overwrite: false
mounts:
  - [ /deb/sdb, /var/cache/image-sync ]
