- name: create dirs
  block:
  - file:
      path: /etc/fedcloud
      state: directory
  - file:
      path: /etc/fedcloud/vos
      state: directory

- name: VO directory
  file:
    path: "/etc/fedcloud/vos/{{ item.key }}"
    state: directory
  loop: "{{ vos | dict2items }}"

- name: VO auth files
  copy:
    content: "{{ item.value.auth.client_id }}"
    dest: "/etc/fedcloud/vos/{{ item.key }}/client_id"
  when: item.value.auth is defined
  loop: "{{ vos | dict2items }}"

- name: VO auth files
  copy:
    content: "{{ item.value.auth.client_secret }}"
    dest: "/etc/fedcloud/vos/{{ item.key }}/client_secret"
  when: item.value.auth is defined
  loop: "{{ vos | dict2items }}"

- name: VO auth files
  copy:
    content: "{{ item.value.auth.refresh_token }}"
    dest: "/etc/fedcloud/vos/{{ item.key }}/refresh_token"
  when: item.value.auth is defined
  loop: "{{ vos | dict2items }}"
