# Default values for fedcloud-ops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

sites:
  # This should be a dict of sites as follows:
  # Name-of-site:
  #   endpoint: https://thekeystone-url/v3
  #   vos:
  #   # a new dict with name of the VO as key
  #     vo1:
  #       auth:
  #         # the id of the project
  #         project: xxx
  #         # cloud-info-provider credentials
  #         cloudInfo:
  #           clientId:
  #           clientSecret:
  #           refreshToken:
  #       # optionally specify a protocol for the Keystone V3 federation API
  #       # default is openid
  #       protocol: openid
  #       defaultNetwork: private | public | private_only | public_only (default is public)
  #       publicNetwork: <name of the public network> (default is UNKNOWN)

cloudInfo:
  debug: false
  # how often should the cloud-info-provider run, default every 5 minutes
  # rethink if this is actually a cronjob or a different thing
  schedule: '*/5 * * * *'
  image:
    # the image with the cloud-info-provider ready to run the job
    repository: enolfc/cloudinfoops
    tag: '0.1.0'
    pullPolicy: IfNotPresent
  ams:
    host: msg-devel.argo.grnet.gr
    project: egi_cloud_info
    # ams credentials, specify either token or cert + key
    token:
    cert:
    key:

cloudkeeper:
  # how to make this a bit random between instances of ck?
  schedule: '25 */5 * * *'
  image:
    # the image with the cloud-info-provider ready to run the job
    repository: cloudkeeper/cloudkeeper
    tag: 2.0.0
    pullPolicy: IfNotPresent
  # authentication for the appdb requires tokens to be specified
  # in the following format
  # # auth:
  #    # <name of the vo>: <token>


cloudkeeperOS:
  service:
    type: ClusterIP
  image:
    # the image with the cloud-info-provider ready to run the job
    repository: enolfc/cloudkeeper-os
    tag: '0.1.0'
    pullPolicy: IfNotPresent


# Everything below comes from helm, should be reviewed

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
