---
- hosts: all
  become: true
  roles:
    - role: "grycap.motley_cue"
      vars:
        ssh_oidc_other_vos_name: cloud.egi.eu
        ssh_oidc_other_vos_role: auditor
      tags:
        - never
    - role: catchall
      vars:
        site_config_dir: ../sites/
