---
- hosts: all
  become: true
  roles:
    - role: "grycap.motley_cue"
      vars:
        ssh_oidc_other_vos_name: cloud.egi.eu
        ssh_oidc_other_vos_role: auditor
      tags:
        - always
    - role: catchall
      vars:
        site_config_dir: ../sites/
        swift:
          site: NCG-INGRID-PT
          vo: vo.access.egi.eu
          container: cloud-info
