---
vos:
  acc-comp.egi.eu:
    auth: "{{ fedcloud_sa }}"
  aquamonitor.c-scale.eu:
    auth: "{{ fedcloud_sa }}"
  belle:
  benchmark.terradue.com:
    auth: "{{ robot_sa }}"
  biinsight.eosc-hub.eu:
    auth: "{{ fedcloud_sa }}"
  bioexcel:
  bioisi:
  biomed:
    auth: "{{ robot_sa }}"
  "/biomed/vip":
    auth: "{{ robot_sa }}"
  blazarmonitoring.asi.it:
    auth: "{{ robot_sa }}"
  chipster.csc.fi:
  cms:
  cloud.egi.eu:
    auth: "{{ fedcloud_sa }}"
  covid19.eosc-synergy.eu:
    auth: "{{ fedcloud_sa }}"
  cos4cloud-eosc.eu:
    auth: "{{ fedcloud_sa }}"
  cryoem.instruct-eric.eu:
    auth: "{{ fedcloud_sa }}"
  d4science.org:
    auth: "{{ fedcloud_sa }}"
  datafurn.eosc-hub.eu:
    auth: "{{ fedcloud_sa }}"
  demo.fedcloud.egi.eu:
    auth: "{{ robot_sa }}"
  drihm.eu:
  dteam:
    auth: "{{ robot_sa }}"
  eiscat.se:
    auth: "{{ robot_sa }}"
  eli-laser.eu:
  enmr.eu:
    auth: "{{ robot_sa }}"
  EOServices-vo.indra.es:
    auth: "{{ fedcloud_sa }}"
  eosc-synergy.eu:
    auth: "{{ fedcloud_sa }}"
  extras-fp7.eu:
  fedcloud.egi.eu:
    auth: "{{ enol_sa }}"
  fusion:
    auth: "{{ robot_sa }}"
  geohazards.terradue.com:
  gosafe.eng.it:
    auth: "{{ fedcloud_sa }}"
  HighResLandSurf.c-scale.eu:
    auth: "{{ fedcloud_sa }}"
  hisea.c-scale.eu:
    auth: "{{ fedcloud_sa }}"
  icecube:
    auth: "{{ fedcloud_sa }}"
  gridifin.ro:
  hidronav.eosc-hub.eu:
  hydrology.terradue.com:
  kampal.eosc-hub.eu:
    auth: "{{ fedcloud_sa }}"
  lagoproject.net:
    auth: "{{ eduteams }}"
  lhcb:
  med.semmelweis-univ.hu:
    auth: "{{ fedcloud_sa }}"
  minka-sdg.org:
    auth: "{{ fedcloud_sa }}"
  mathematical-software:
  mswss.ui.savba.sk:
    auth: "{{ fedcloud_sa }}"
  mteam.data.kit.edu:
    auth: "{{ fedcloud_sa }}"
  o3as.data.kit.edu:
    auth: "{{ fedcloud_sa }}"
  opencoast.eosc-hub.eu:
    auth: "{{ robot_sa }}"
  openrisknet.org:
    auth: "{{ fedcloud_sa }}"
  ops:
    auth: "{{ robot_sa }}"
  peachnote.com:
    auth: "{{ fedcloud_sa }}"
  return.c-scale.eu:
    auth: "{{ fedcloud_sa }}"
  saps-vo.i3m.upv.es:
    auth: "{{ fedcloud_sa }}"
  training.egi.eu:
    auth: "{{ fedcloud_sa }}"
  umsa.cerit-sc.cz:
    auth: "{{ fedcloud_sa }}"
  university.eosc-synergy.eu:
    auth: "{{ fedcloud_sa }}"
  verce.eu:
  vo.access.egi.eu:
    auth: "{{ fedcloud_sa }}"
  vo.agiliacenter.com:
    auth: "{{ fedcloud_sa }}"
  vo.bd4nrg.eu:
    auth: "{{ fedcloud_sa }}"
  vo.carouseldancing.org:
    auth: "{{ fedcloud_sa }}"
  vo.cite.gr:
    auth: "{{ fedcloud_sa }}"
  vo.clarin.eu:
  vo.crmdr.org:
  vo.dariah.eu:
  vo.deltares.nl:
    auth: "{{ fedcloud_sa }}"
  vo.digitbrain.eu:
    auth: "{{ fedcloud_sa }}"
  vo.elixir-europe.org:
  vo.eoscfuture-sp.panosc.eu:
  vo.emphasisproject.eu:
    auth: "{{ fedcloud_sa }}"
  vo.emsodev.eu:
  vo.emso-eric.eu:
    auth: "{{ fedcloud_sa }}"
  vo.enes.org:
    auth: "{{ fedcloud_sa }}"
  vo.envri-fair.eu:
    auth: "{{ fedcloud_sa }}"
  vo.environmental.egi.eu:
    auth: "{{ fedcloud_sa }}"
  vo.eurogeoss.eu:
    auth: "{{ fedcloud_sa }}"
  vo.europlanet-vespa.eu:
  vo.formation.idgrilles.fr:
  vo.france-grilles.fr:
  vo.geoss.eu:
    auth: "{{ fedcloud_sa }}"
  vo.grand-est.fr:
  vo.iiasa.ac.at:
  vo.inactive-sarscov2.eu:
  vo.indigo-datacloud.eu:
  vo.lethe-project.eu:
    auth: "{{ fedcloud_sa }}"
  vo.lifewatch.eu:
    auth: "{{ fedcloud_sa }}"
  "/vo.lifewatch.eu/openbiomap":
    auth: "{{ fedcloud_sa }}"
  vo.matrycs.eu:
    auth: "{{ fedcloud_sa }}"
  vo.mightee.idia.za:
    auth: "{{ fedcloud_sa }}"
  vo.mrilab.es:
  vo.nbis.se:
  vo.neanias.eu:
    auth: "{{ fedcloud_sa }}"
  vo.nextgeoss.eu:
    auth: "{{ fedcloud_sa }}"
  vo.notebooks.egi.eu:
    auth: "{{ fedcloud_sa }}"
  vo.obsea.es:
    auth: "{{ fedcloud_sa }}"
  vo.openrdm.eu:
    auth: "{{ fedcloud_sa }}"
  vo.operas-eu.org:
    auth: "{{ fedcloud_sa }}"
  vo.pangeo.eu:
    auth: "{{ fedcloud_sa }}"
  vo.panosc.eu:
    auth: "{{ fedcloud_sa }}"
  vo.phiri.eu:
    auth: "{{ fedcloud_sa }}"
  vo.plocan.eu:
    auth: "{{ fedcloud_sa }}"
  vo.policycloud.eu:
    auth: "{{ fedcloud_sa }}"
  vo.sbg.in2p3.fr:
  vo.stars4all.eu:
    auth: "{{ fedcloud_sa }}"
  dih-voucher01.eosc-hub.eu:
  vo.max-centre.eu:
    auth: "{{ fedcloud_sa }}"
  waterwatch.c-scale.eu:
    auth: "{{ fedcloud_sa }}"
  worsica.vo.incd.pt:
    auth: "{{ fedcloud_sa }}"
