{{- $values := .Values -}}
{{- range $site, $siteConf := .Values.sites }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloud-info-provider-{{ $site | lower }}
spec:
  schedule: {{ $values.cloudInfo.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cloud-info
            image: "{{ $values.cloudInfo.image.repository }}:{{ $values.cloudInfo.image.tag }}"
            imagePullPolicy: {{ $values.cloudInfo.image.pullPolicy }}
            command: ["/usr/local/bin/ams-wrapper.sh"]
            env:
            - name: OS_AUTH_URL
              value: {{ $siteConf.endpoint }}
            - name: OS_AUTH_TYPE
              value: v3oidcaccesstoken
            - name: OS_IDENTITY_PROVIDER
              value: egi.eu
            - name: OS_PROTOCOL
              value: openid
            - name: CHECKIN_CLIENT_ID_FILE
              value: /etc/checkin/client_id
            - name: CHECKIN_CLIENT_SECRET_FILE
              value: /etc/checkin/client_secret
            - name: CHECKIN_REFRESH_TOKEN_FILE
              value: /etc/checkin/refresh_token
            - name: CLOUD_INFO_CONFIG
              value: /etc/cloud-info-provider/site/site.yaml
            - name: SITE_NAME
              value: {{ $site }}
            - name: AMS_TOKEN_FILE
              value: /etc/ams/token
            volumeMounts:
            - mountPath: /etc/cloud-info-provider/site
              name: cloud-info-config
            - mountPath: /etc/checkin/
              name: checkin-secret
            - mountPath: /etc/ams
              name: ams-secret
            resources:
{{ toYaml $values.resources | indent 14 }}
          volumes:
          - name: cloud-info-config
            configMap:
              name: cloud-info-config-{{ $site | lower }}
              items:
              - key: site.yaml
                path: site.yaml
          - name: checkin-secret
            secret:
              secretName: checkin-secret
          - name: ams-secret
            secret:
              secretName: ams-secret
        {{- with $values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with $values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
{{- end }}
