apiVersion: v1
kind: Secret
metadata:
  name: checkin-secret
type: Opaque
data:
  client_id: {{ .Values.auth.clientId | b64enc | quote }}
  client_secret: {{ .Values.auth.clientSecret | b64enc | quote }}
  refresh_token: {{ .Values.auth.refreshToken | b64enc | quote }}
