---
name: Check links

on: [pull_request]

permissions: read-all

jobs:
  markdown-link-check:
    name: Check links using markdown-link-check
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check links on new changes
        uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225
        with:
          config-file: ".github/linters/mlc_config.json"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          base-branch: "main"
