---
name: "Deploy cloud-info"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "deploy/**"

permissions: read-all

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      dir: "deploy/cloud-info"
      tags: "cloud-info,docker"
      env: "cloud-info"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ANSIBLE_SECRETS: ${{ secrets.ANSIBLE_SECRETS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #DEPLOY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
