---
name: Deploy

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      tags:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      ANSIBLE_SECRETS:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      DEPLOY_GITHUB_TOKEN:
        required: true

permissions:
  issues: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    env:
      TF_VAR_flavor_id: ${{ vars.TF_VAR_FLAVOR_ID }}
      TF_VAR_image_id: ${{ vars.TF_VAR_IMAGE_ID }}
      TF_VAR_net_id: ${{ vars.TF_VAR_NET_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.x
      - name: Install environment
        run: |
          curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 > jq
          chmod +x jq
          # Forcing the use of fedcloudclient integrated with cloud-info-api
          pip install simplejson yq git+https://github.com/enolfc/fedcloudclient.git@cloud-info
      - name: Configure providers access
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ANSIBLE_SECRETS: ${{ secrets.ANSIBLE_SECRETS }}
          INPUTS_DIR: ${{ inputs.dir }}
        run: |
          ./deploy/site-config.sh "${INPUTS_DIR}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_version: 1.2.9
      - name: Terraform Format
        id: fmt
        run: |
          cd "${INPUTS_DIR}"
          terraform fmt -check
        env:
          INPUTS_DIR: ${{ inputs.dir }}
      - name: Terraform init
        id: init
        run: |
          cd "${INPUTS_DIR}"
          terraform init
        env:
          INPUTS_DIR: ${{ inputs.dir }}
      - name: Adjust cloud-init file
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          INPUTS_DIR: ${{ inputs.dir }}
          INPUTS_TAGS: ${{ inputs.tags }}
        run: |
          cd "${INPUTS_DIR}"
          cat ../cloud-init.yaml extra-cloud-init.yaml > cloud-init.yaml
          sed -i -e "s/%TOKEN%/${{ secrets.DEPLOY_GITHUB_TOKEN }}/" cloud-init.yaml
          sed -i -e "s/%TAGS%/${INPUTS_TAGS}/" cloud-init.yaml
          sed -i -e "s/%REF%/${{ github.sha }}/" cloud-init.yaml
          sed -i -e "s/%SHORT_REF%/$(git rev-parse --short HEAD)/" cloud-init.yaml
          sed -i -e "s#%SLACK_WEBHOOK_URL%#$SLACK_WEBHOOK_URL#" cloud-init.yaml
          sed -i -e "s/%FEDCLOUD_LOCKER_TOKEN%/$FEDCLOUD_LOCKER_TOKEN/" cloud-init.yaml
          sed -i -e "s/%CLOUDS_YAML%/$(base64 -w 0 < clouds.yaml)/" cloud-init.yaml
      - name: terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          cd "${INPUTS_DIR}"
          terraform plan -no-color
        continue-on-error: true
        env:
          INPUTS_DIR: ${{ inputs.dir }}
      - name: Update Pull Request
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
          ACTOR: "${{ github.actor }}"
          EVENT_NAME: "${{ github.event_name }}"
          FMT_OUTCOME: "${{ steps.fmt.outcome }}"
          PLAN_OUTCOME: "${{ steps.plan.outcome }}"
          INIT_OUTCOME: "${{ steps.init.outcome }}"
        with:
          github-token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${process.env.FMT_OUTCOME}\`
            #### Terraform Initialization ⚙️\`${process.env.INIT_OUTCOME}\`
            #### Terraform Plan 📖\`${process.env.PLAN_OUTCOME}\`
            <details><summary>Show Plan</summary>

            \`\`\`
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${process.env.ACTOR}, Action: \`${process.env.EVENT_NAME}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        id: terraform-apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd "${INPUTS_DIR}"
          terraform apply -auto-approve
        env:
          INPUTS_DIR: ${{ inputs.dir }}
      - name: Get VM ID
        id: terraform-vm-id
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd "${INPUTS_DIR}"
          terraform output -raw instance-id
        env:
          INPUTS_DIR: ${{ inputs.dir }}
      - name: Re-configure providers access
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          INPUTS_DIR: ${{ inputs.dir }}
        run: |
          # using parametric scopes to only have access to cloud.egi.eu VO
          SCOPE="openid%20email%20profile%20voperson_id"
          SCOPE="$SCOPE%20eduperson_entitlement:urn:mace:egi.eu:group:cloud.egi.eu:role=vm_operator#aai.egi.eu"
          SCOPE="$SCOPE%20eduperson_entitlement:urn:mace:egi.eu:group:cloud.egi.eu:role=member#aai.egi.eu"
          SCOPE="$SCOPE%20entitlements:urn:mace:egi.eu:group:cloud.egi.eu:role=vm_operator#aai.egi.eu"
          SCOPE="$SCOPE%20entitlements:urn:mace:egi.eu:group:cloud.egi.eu:role=member#aai.egi.eu"
          OIDC_TOKEN=$(curl -X POST "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/token" \
                            -d "grant_type=client_credentials&client_id=$CLIENT_ID&scope=$SCOPE&client_secret=$CLIENT_SECRET" \
                          | jq -r ".access_token")
          echo "::add-mask::$OIDC_TOKEN"
          cd "${INPUTS_DIR}"
          cp ../clouds.yaml .
          BACKEND_SITE="$(yq -r .clouds.backend.site clouds.yaml)"
          BACKEND_VO="$(yq -r .clouds.backend.vo clouds.yaml)"
          BACKEND_OS_TOKEN="$(fedcloud openstack token issue --oidc-access-token "$OIDC_TOKEN" \
                                                             --site "$BACKEND_SITE" --vo "$BACKEND_VO" -j | jq -r '.[0].Result.id')"
          echo "::add-mask::$BACKEND_OS_TOKEN"
          echo "BACKEND_OS_TOKEN=$BACKEND_OS_TOKEN" >> "$GITHUB_ENV"
          sed -i -e "s/backend_secret/$BACKEND_OS_TOKEN/" clouds.yaml
          mkdir -p ~/.config/openstack
          touch ~/.config/openstack/secure.yaml
      - name: Get the status file from swift
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60
        with:
          timeout_minutes: 10
          max_attempts: 30
          retry_wait_seconds: 60
          command: >
            pushd "${{ inputs.dir }}" \
              && openstack --os-cloud backend \
                --os-token "$BACKEND_OS_TOKEN" object save fedcloud-catchall \
                 "${{ steps.terraform-vm-id.outputs.stdout }}" \
              && openstack --os-cloud backend \
                --os-token "$BACKEND_OS_TOKEN" object delete \
                fedcloud-catchall "${{ steps.terraform-vm-id.outputs.stdout }}"
      - name: Look for errors
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd "${INPUTS_DIR}"
          # show the status in the build log
          cat "${STEPS_TERRAFORM_VM_ID_OUTPUTS_STDOUT}"
          grep -v "error" "${STEPS_TERRAFORM_VM_ID_OUTPUTS_STDOUT}"
        env:
          INPUTS_DIR: ${{ inputs.dir }}
          STEPS_TERRAFORM_VM_ID_OUTPUTS_STDOUT: ${{ steps.terraform-vm-id.outputs.stdout }}
