---
name: Lint

on: pull_request

permissions: read-all

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint files
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status Checks
      statuses: write

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Full git history needed to get proper list of changed files
          fetch-depth: 0
          persist-credentials: false

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Fail on errors
          DISABLE_ERRORS: false
          # biome conflicts with prettier
          VALIDATE_BIOME_FORMAT: false
          # pylint is too much at the moment, potentially removed in the future
          VALIDATE_PYTHON_PYLINT: false
          # conflicts with black
          VALIDATE_PYTHON_RUFF_FORMAT: false
          # Disabling this file as it gets confused
          FILTER_REGEX_EXCLUDE: ".*.env.j2"
          # Fix clone errors found in PR 575
          LINTER_RULES_PATH: ".github/linters"
