---
name: Test role

on: [push, pull_request]

jobs:
  molecule:
    name: Runs molecule for the ansible role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ">=3.9"
      - name: Install dependencies
        run: |
          pip install "ansible-core>=2.20.0,<2.21.0" \
                      "molecule==26.4.0" \
                      "molecule-plugins[docker]==25.8.12" \
                      pytest pytest-testinfra
      - name: Install Ansible Docker Collection
        run: |
          ansible-galaxy collection install community.docker
      - name: Verify Docker is running
        run: docker info
      - name: Test Ansible Bootstrap
        run: |
          cd deploy/roles/catchall
          molecule --debug test
        env:
          PY_COLORS: 1
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}/deploy/roles
