---
name: Test role

on: [push, pull_request]

permissions: read-all

jobs:
  molecule:
    name: Runs molecule for the ansible role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ">=3.9"
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Install dependencies
        run: |
          uv sync --locked --group molecule
      - name: Test Ansible Bootstrap
        run: |
          cd deploy/roles/catchall
          uv run molecule test --report --command-borders
        env:
          PY_COLORS: 1
          ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:${GITHUB_WORKSPACE}/deploy/roles
