name: Testing and validation

on:
  - pull_request
  - push

permissions: read-all

jobs:
  test:
    name: Test and validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # Check yaml files comply to schema
      - name: Check YAML schema
        run: |
          curl -L https://github.com/neilpa/yajsv/releases/download/v1.4.0/yajsv.linux.amd64 > yajsv
          chmod +x yajsv
          ./yajsv -s schema.json sites/*.yaml
      # Python
      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - name: Install the project
        run: |
          uv sync --locked --all-groups
      - name: Run tests
        run: |
          uv run py.test --cov=fedcloud_catchall --cov-report=xml --cov-report=term-missing src/fedcloud_catchall/
      # Validation
      - name: Validate GOC and VOs
        run: |
          alias yq="uv run yq"
          ./validate.sh
